### ISSUE TITLE
Password issue, no ffxiscripting

### ISSUE THREAD

**Issue by colebudffxi** [matthamptonasic/Iocaine#35]
Good morning, 
ffxiscripting is now down and password cannot be retrieved anymore. Is there another way to obtain the password?

**Comment by matthamptonasic** [comment]
I had no idea the site went down, but it's likely because Iocaine support stopped a few months ago due to my hosting service deprecating support that I used to host the Iocaine server interface.
As far as I recall, the password is 'SorryForTheDelay' (no quotes).  I'm now happy for anyone to use it at will, please feel free to share the password or anything else about it you like.
However, if my hosting service isn't supporting what my server is written in, I don't think the password matters.  Unless you can get a binary that bypasses the password and all server connections, it still won't work.

**Comment by colebudffxi** [comment]
Thank you for your time and response. It was a good run while it was up!
Sadly, the rest of what you said is way above me. Thank you for contacting
back.

**Comment by matthamptonasic** [comment]
Happy to and sorry it's going away.  It was a fantastic experience for me, I hope it was for others as well.  Thanks!
